name: causality-nd
channels:
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - networkx
  - statsmodels
  - pytest
  - pip
  - pip:
    - causal-learn
    - causallib
    - nbformat
    - nbconvert
    - jupyter
    - ipykernel
    - pytest-timeout
